import type { ProjectReport } from "@/lib/reports/types";

export const REPORT: ProjectReport = {
  slug: "helix-studio",
  title: "Helix Studio",
  tagline: "An AI operating system for software engineering.",
  year: "2026",
  role: "Solo: product, architecture, full-stack and AI",
  treatment: "full",
  cover: {
    src: "/work/helix-agents.png",
    alt: "Helix Studio landing page showing the multi-agent pipeline running a build",
    caption: "The multi-agent pipeline. Each specialist confirms its work before the next begins.",
  },
  intro:
    "Helix Studio is a full AI software-engineering platform in the class of Cursor, Windsurf, and Claude Code, except it is built around a pipeline of specialist agents instead of one assistant doing everything. You connect a repository, describe a change in plain English, and the pipeline plans it, writes it, reviews it, audits it, and hands you something you can actually ship. It is live at helixstudio.org.",
  sections: [
    {
      id: "overview",
      heading: "Overview",
      body: [
        "Helix is a Next.js 16 application with 93 API routes, around 30 Prisma models, a Monaco editor, an xterm terminal, and a seven-phase agent pipeline at its core. It supports building from scratch or importing a real repository from GitHub, GitLab, Bitbucket, Azure, or Gitea, and it previews everything it builds in an isolated cloud microVM before you decide to keep it.",
        "The honest pitch: most AI coding tools autocomplete. Helix tries to own a change end to end, the way a small engineering team would, with a planner, a builder, a reviewer, and auditors that each leave a paper trail.",
      ],
    },
    {
      id: "problem",
      heading: "The problem",
      body: [
        "A single AI assistant bolted onto an editor is great at the next line and bad at the whole job. Nobody plans the work, checks it against the rest of the codebase, hardens it, or verifies it actually runs before handing it back. The result is code that looks plausible and behaves mysteriously.",
        "I wanted the opposite: shipping treated as a pipeline of specialized responsibilities, where every step is inspectable and every generated line can explain why it exists.",
      ],
    },
    {
      id: "architecture",
      heading: "The seven-phase pipeline",
      body: [
        "A build request runs through seven specialists in order: Planner, Repository Analyzer, Architect, Engineer, Reviewer, Security Auditor, and Performance Auditor. The Planner decomposes the request into a numbered plan. The Analyzer reads the file tree and package.json to detect the stack, deterministically and for zero tokens. The Architect writes a one-sentence technical approach. Then the Engineer, the only phase that must succeed, does the actual building with tools that read, search, and write files.",
        "The last three phases are quality control: a Reviewer reads the diff and issues a ship-it or hold verdict, a Security Auditor runs static analysis for secrets, injection patterns, and risky dependencies, and a Performance Auditor measures bundle weight. Every phase except the Engineer degrades gracefully, so a hiccup in planning never blocks a build. Progress streams to the browser as line-delimited JSON over a single stream, which turned out to be simpler and more reliable than websockets.",
      ],
    },
    {
      id: "stack-choices",
      heading: "Why this stack",
      body: [
        "Next.js 16 with React 19 gives one deployable unit for marketing, the studio, and all 93 API routes. PostgreSQL through Prisma 7 holds everything from users to the intent ledger. Auth.js v5 handles sessions with credentials, GitHub, Google, and a guest mode that creates a real account with a small token allowance, so people can try the product without a signup wall.",
        "The AI layer is deliberately multi-provider: Anthropic, OpenAI, Gemini, AWS Bedrock, and local OpenAI-compatible servers all plug into one interface. Anthropic requests use prompt caching on the system prompt and tool definitions, which makes multi-hop agent turns roughly 90 percent cheaper on input tokens. Model names are white-labeled so users pick by capability, not by vendor logo.",
      ],
    },
    {
      id: "services",
      heading: "How the pieces talk",
      body: [
        "The studio UI posts a build request to the workspace chat route, which streams NDJSON events back: phase updates, token counts, and a change manifest of written and deleted files so the file tree updates live. Upstash Redis carries the progress channel and rate limiting so both survive serverless instances coming and going. Git hosts are called with plain fetch against their REST APIs, no SDK, through one adapter interface per host.",
        "Code the agents write does not touch the real repository. It lands in a virtual overlay, one database row per created, modified, or deleted file, layered over the base repo. Pushing to the actual git host is a separate, explicit button. That one design decision is what makes the whole thing safe to let an AI loose on.",
      ],
    },
    {
      id: "data-flow",
      heading: "One build, end to end",
      body: [
        "You connect a repo and Helix creates a workspace that mirrors it, reading files on demand with your OAuth token. Ask for a change and the pipeline kicks off: plan, analyze, approach, build. The Engineer works in hops, up to 24 per turn, reading and searching in parallel and writing sequentially, verifying its own work by running builds and tests inside a Vercel Sandbox microVM.",
        "The sandbox boots your app on a public preview URL that the studio embeds in an iframe, and previews self-destruct after 15 minutes because forgotten VMs are just money with a fan attached. When you like what you see, you push, and the deploy integration links the repo to Vercel, Netlify, Cloudflare, or Render so their native CI builds on every push.",
      ],
    },
    {
      id: "security",
      heading: "Security and the intent ledger",
      body: [
        "Sessions are 30-day JWTs revalidated against the database, password resets invalidate every session through a fingerprint baked into the token, and OAuth tokens live server-side only. A user's own AI key always works, but the platform's keys never spend for free accounts by accident. The token budget is reserved atomically before a turn starts, which closed a race where two concurrent turns could double-spend a quota.",
        "The intent ledger is my favorite part: every generated line links back to the request that asked for it, the plan step it belongs to, and full before-and-after snapshots. That enables intentional undo, where you reverse an idea instead of a commit. It also means the answer to 'why does this line exist' is a database query, not archaeology.",
      ],
    },
    {
      id: "challenges",
      heading: "Challenges and honest tradeoffs",
      body: [
        "Serverless statelessness was the recurring boss fight. The sandbox itself became the state store: VMs are found again by name, logs are read from a file inside the VM, and status is inferred by probing the app. Dependency installs were the slowest step, so environment snapshots cache installed node_modules keyed by a hash of the lockfile, with a seven-day shelf life.",
        "I also ran an adversarial QA audit against my own product and it found real issues, including a cross-tenant data leak in a legacy route and that quota double-spend race. All of it got fixed and several fixes are annotated in the code. Only some pipeline phases are model calls; the analyzer and both auditors are deterministic heuristics, and I kept it that way on purpose. Determinism is free, fast, and never hallucinates.",
      ],
    },
    {
      id: "outcomes",
      heading: "Outcomes",
      body: [
        "Helix is live at helixstudio.org with 64 passing unit tests, 9 passing end-to-end tests, and a homepage demo that autoplays the pipeline. It ships 24 built-in engineering skills, from test-driven development to security hardening, that bias the agents toward opinionated output. There is even an Electron desktop build for local shell access.",
        "Most importantly, the architecture survived contact with reality: the overlay model, the atomic token budget, and the graceful-degradation pipeline all came out of real failures, and each one made the product harder to break.",
      ],
    },
  ],
  diagram: {
    caption: "A build request moving through the pipeline to a live preview.",
    groups: [
      { id: "studio", label: "Studio", nodeIds: ["web", "api"] },
      { id: "pipeline", label: "Agent pipeline", nodeIds: ["planner", "analyzer", "architect", "engineer", "reviewer", "security", "perf"] },
      { id: "infra", label: "Data and infra", nodeIds: ["db", "redis", "models", "git", "sandbox"] },
    ],
    nodes: [
      {
        id: "web",
        label: "Studio editor",
        tech: "Next.js 16 + Monaco",
        icon: "AppWindow",
        accent: "aqua",
        col: 0,
        row: 0,
        detail: {
          what: "The browser workspace: file tree, editor tabs, chat, terminal, and a live preview iframe.",
          why: "One Next.js app serves marketing, studio, and 93 API routes, so there is exactly one thing to deploy.",
        },
      },
      {
        id: "api",
        label: "Chat route",
        tech: "NDJSON stream",
        icon: "Radio",
        accent: "aqua",
        col: 1,
        row: 0,
        detail: {
          what: "The workspace chat endpoint that runs a build and streams phase events, tokens, and file changes live.",
          why: "Line-delimited JSON over one HTTP stream is simpler than websockets and survives serverless just fine.",
          protocol: "POST + streamed application/x-ndjson",
        },
      },
      {
        id: "planner",
        label: "Planner",
        tech: "model call",
        icon: "ListChecks",
        accent: "iris",
        col: 0,
        row: 1,
        detail: {
          what: "Decomposes the request into a numbered 3 to 7 step plan that the Engineer receives as a brief.",
          why: "A cheap planning pass keeps the expensive build turn focused instead of wandering.",
        },
      },
      {
        id: "analyzer",
        label: "Repo Analyzer",
        tech: "deterministic, 0 tokens",
        icon: "Search",
        accent: "iris",
        col: 1,
        row: 1,
        detail: {
          what: "Reads the file tree and package.json to detect framework, auth, and database.",
          why: "Stack detection does not need a model. Deterministic code is free and never hallucinates a framework.",
        },
      },
      {
        id: "architect",
        label: "Architect",
        tech: "model call",
        icon: "Layers",
        accent: "iris",
        col: 2,
        row: 1,
        detail: {
          what: "Writes a one-sentence technical approach grounded in the plan plus the detected stack.",
          why: "A tiny approach statement keeps the Engineer from reinventing the codebase's own patterns.",
        },
      },
      {
        id: "engineer",
        label: "Engineer",
        tech: "agent turn, 24 hops",
        icon: "Braces",
        accent: "iris",
        col: 3,
        row: 1,
        detail: {
          what: "The build agent. Reads, searches, writes files through tools, and verifies its own work in the sandbox.",
          why: "The only phase that must succeed. Reads run in parallel, writes run sequentially for deterministic ordering.",
        },
      },
      {
        id: "reviewer",
        label: "Reviewer",
        tech: "diff review",
        icon: "MessageSquare",
        accent: "ember",
        col: 0,
        row: 2,
        detail: {
          what: "Reads the changed-file diff and issues a ship-it or hold verdict.",
          why: "A second set of eyes on the diff, exactly like code review, but it never gets tired or grumpy.",
        },
      },
      {
        id: "security",
        label: "Security auditor",
        tech: "SAST, 0 tokens",
        icon: "ShieldCheck",
        accent: "ember",
        col: 1,
        row: 2,
        detail: {
          what: "Static analysis for hardcoded secrets, injection patterns, unsafe DOM writes, and risky dependencies.",
          why: "Findings are advisory, never a silent block. Deterministic scanning beats security theater.",
        },
      },
      {
        id: "perf",
        label: "Perf auditor",
        tech: "bundle analysis, 0 tokens",
        icon: "Gauge",
        accent: "ember",
        col: 2,
        row: 2,
        detail: {
          what: "Measures bundle weight and flags heavy additions before they ship.",
          why: "Performance regressions are cheapest to catch in the same run that created them.",
        },
      },
      {
        id: "sandbox",
        label: "Vercel Sandbox",
        tech: "Firecracker microVM",
        icon: "Rocket",
        accent: "aqua",
        col: 3,
        row: 2,
        detail: {
          what: "An isolated VM that installs, builds, tests, and serves a live preview URL for the workspace.",
          why: "Real verification needs a real runtime. Previews self-destruct after 15 minutes to cap cost.",
          protocol: "exec over the Sandbox API, preview over HTTPS",
        },
      },
      {
        id: "models",
        label: "Model providers",
        tech: "Anthropic + OpenAI + Bedrock",
        icon: "Sparkles",
        accent: "iris",
        col: 3,
        row: 3,
        detail: {
          what: "Model routing across five providers, with prompt caching on Anthropic agent turns.",
          why: "The right model per phase, and caching makes multi-hop turns about 90 percent cheaper on input.",
          protocol: "Messages API + OpenAI-compatible chat completions",
        },
      },
      {
        id: "db",
        label: "PostgreSQL",
        tech: "Prisma 7",
        icon: "Database",
        accent: "neutral",
        col: 0,
        row: 3,
        detail: {
          what: "Workspaces, the file overlay, messages, the intent ledger, billing, and about 30 models total.",
          why: "The overlay lives here too: one row per changed file, layered over the base repo, so nothing touches real code until you push.",
        },
      },
      {
        id: "redis",
        label: "Upstash Redis",
        tech: "progress + rate limit",
        icon: "Zap",
        accent: "neutral",
        col: 1,
        row: 3,
        detail: {
          what: "Carries the live progress channel and the rate limiter across serverless instances.",
          why: "Serverless functions do not share memory, so anything two instances must agree on lives here.",
        },
      },
      {
        id: "git",
        label: "Git hosts",
        tech: "GitHub + 4 more",
        icon: "GitBranch",
        accent: "neutral",
        col: 2,
        row: 3,
        detail: {
          what: "Repo reads and explicit pushes against GitHub, GitLab, Bitbucket, Azure, and Gitea.",
          why: "Plain fetch against each host's REST API behind one adapter interface. No SDK lock-in.",
          protocol: "REST over HTTPS with the user's OAuth token or PAT",
        },
      },
    ],
    edges: [
      { from: "web", to: "api", label: "build request" },
      { from: "api", to: "planner", label: "pipeline start" },
      { from: "planner", to: "analyzer" },
      { from: "analyzer", to: "architect" },
      { from: "architect", to: "engineer", label: "brief" },
      { from: "engineer", to: "reviewer", label: "diff" },
      { from: "reviewer", to: "security" },
      { from: "security", to: "perf" },
      { from: "engineer", to: "sandbox", label: "build + test", kind: "sync" },
      { from: "engineer", to: "models", label: "agent turns", kind: "data" },
      { from: "api", to: "redis", label: "progress", kind: "data" },
      { from: "api", to: "db", label: "overlay + ledger", kind: "data" },
      { from: "engineer", to: "git", label: "explicit push", kind: "async" },
      { from: "sandbox", to: "web", label: "preview URL" },
    ],
  },
  gallery: [
    {
      src: "/work/helix-build.png",
      alt: "Helix Studio build entry screen asking what the user wants to build",
      caption: "Plain-English intake. Describe what you want and the pipeline takes it from there.",
    },
  ],
  stack: ["Next.js 16", "React 19", "TypeScript", "Prisma 7", "PostgreSQL", "Auth.js v5", "Anthropic", "OpenAI", "Vercel Sandbox", "Upstash Redis", "Stripe", "Sentry"],
  results: [
    { value: "7", label: "Specialist agents in the pipeline" },
    { value: "93", label: "API routes in one Next.js app" },
    { value: "24", label: "Built-in engineering skills" },
    { value: "Live", label: "Deployed at helixstudio.org" },
  ],
  links: { live: "https://helixstudio.org" },
  chat: {
    suggestedQuestions: [
      "How does the seven-phase agent pipeline work?",
      "How does Helix keep AI changes from touching my real repo?",
      "What is the intent ledger?",
    ],
    extraKnowledge: [
      "Token quotas: guest accounts get 15,000 tokens lifetime, free 100K per month, pro 25M, team 100M. Pro is 20 dollars a month and Team 99.",
      "The agent turn allows up to 24 hops and 220K tokens (admins get 48 and 500K). Anthropic output is capped at 32K per call.",
      "Model routing covers openai, anthropic, gemini, local OpenAI-compatible servers, and AWS Bedrock. Free-tier users get white-labeled Bedrock GPT-OSS models; premium unlocks the house engine.",
      "The homepage demo is deliberately a scripted client-side simulation driven by a single cursor value so the terminal, agent lanes, and progress bar can never desync. The real pipeline runs on /build.",
      "The environment snapshot cache keys on a hash of package.json plus lockfiles and expires after 7 days. Sandbox VMs get 2 vCPUs and self-destruct 15 minutes after a preview.",
      "There is a desktop Electron app that bundles the Next.js standalone build for real local shell access.",
    ].join("\n"),
  },
  seo: {
    schemaType: "SoftwareApplication",
    description:
      "Deep dive into Helix Studio, an AI software-engineering platform where a seven-phase pipeline of specialist agents plans, builds, reviews, audits, and ships code with a full intent ledger.",
  },
};
